### ISSUE TITLE
Need Help With Bug Using Example Code

### ISSUE THREAD

**Issue by mpayne-bsi** [fileformat-words/FileFormat.Words-for-.NET#29]
I wasn't sure where to ask for help: here or email. I am using Vis Studio 2022, .Net 8.0. I'm using code from one of the gists for reading tables from a document as my guide:

`string path = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
System.Diagnostics.Debug.WriteLine("HERE IT IS " + path);

string fromName = Path.Combine(path, "Original.docx");
System.Diagnostics.Debug.WriteLine("HERE IT IS " + fromName);
         
var fromdoc = new FileFormat.Words.Document(fromName);
var frombody = new FileFormat.Words.Body(fromdoc);
var tables = frombody.Tables;`

At the FileFormat.Words.Document(fromName) line, I get the following error:

`Exception thrown: 'FileFormat.Words.FileFormatException' in FileFormat.Words.dll
An exception of type 'FileFormat.Words.FileFormatException' occurred in FileFormat.Words.dll but was not handled in user code
Error in Operation Loading Document from file at FileFormat.Words: Error in operation Load OOXML Elements at OpenXML.Words.Data : Error in operation Load Table at OpenXML.Words.Data : Error in operation Load Paragraph at OpenXML.Words.Data : Object reference not set to an instance of an object. 
`

The full error is in the attached file.

The Debug.WriteLine output is:

HERE IT IS C:\Users\mfp\source\repos\WinFormsApp1\bin\Debug\net8.0-windows
HERE IT IS C:\Users\mfp\source\repos\WinFormsApp1\bin\Debug\net8.0-windows\Original.docx

I have verified that the file is in the above folder, and all users have "Full Control" permission.

Any help is appreciated.
[error.txt](https://github.com/user-attachments/files/16254238/error.txt)

**Comment by sabir-aspose** [comment]
@mpayne-bsi From the exception raised, it looks like FileFormat.Words is unable to load all elements from the document you tried to load. For further investigation, may you share the document called "Original.docx"? If the document is confidential, please feel free to share it via email words@fileformat.dev. thanks

**Comment by sabir-aspose** [comment]
@mpayne-bsi Thanks for providing your document via email. The issue has been fixed in [v24.7.1](https://github.com/fileformat-words/FileFormat.Words-for-.NET/releases/tag/v24.7.1) hotfix. The nuget package will be published later but you can download latest binary: [FileFormat.Words.dll](https://github.com/fileformat-words/FileFormat.Words-for-.NET/releases/download/v24.7.1/FileFormat.Words.dll) 

Your provided document was tested with this gist: [C# Read Word Document Tables](https://gist.github.com/fileformat-words-gists/fb5d9fa3c0576b45140ee3be87405c79). The gists works seamlessly using [FileFormat.Words.dll](https://github.com/fileformat-words/FileFormat.Words-for-.NET/releases/download/v24.7.1/FileFormat.Words.dll).

Please feel free to raise any issues you come across.
